-- ============================================================================
-- Esquema Supabase para el módulo de nutrición adaptativa (estilo MacroFactor)
-- Unifica las secciones 10 y 11 de docs/MATH.md en un diseño MVP coherente.
--
-- Aplicar con:  supabase db reset   (o pegar en el SQL editor del proyecto)
-- Requiere auth de Supabase habilitado (tabla auth.users).
-- ============================================================================

-- 1) perfiles: configuración del usuario + TDEE estimado actual
create table if not exists public.perfiles (
  id uuid references auth.users not null primary key,
  updated_at timestamptz default now(),
  altura_cm int,
  deficit_objetivo float not null default 0.15,  -- 0.15 = 15%, 0.20 = 20%
  tdee_actual int not null default 2500,          -- gasto estimado (se recalcula)
  objetivo text not null default 'cut'
    check (objetivo in ('cut','bulk','maintenance','custom'))
);

-- 2) registros_diarios: el corazón del algoritmo (1 fila por día)
create table if not exists public.registros_diarios (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  fecha date not null default current_date,
  peso_kg float,                    -- peso en ayunas
  calorias_consumidas int default 0,
  proteinas_g int default 0,
  carbohidratos_g int default 0,
  grasas_g int default 0,
  agua_ml int default 0,            -- control de 3 litros (diferencial del usuario)
  unique (user_id, fecha)          -- solo un registro por día
);
create index if not exists registros_diarios_user_fecha
  on public.registros_diarios (user_id, fecha);

-- 3) checkins: resultado del recomputo semanal (lo escribe compute_weekly)
create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  week_start date not null,
  estimated_tdee numeric,
  target_intake_kcal numeric,
  delta_peso_kg numeric,
  promedio_calorias numeric,
  confidence numeric,
  unique (user_id, week_start)
);

-- 4) alimentos: caché local del escáner de código de barras (Open Food Facts)
create table if not exists public.alimentos (
  barcode text primary key,
  name text,
  kcal_100g numeric,
  protein_100g numeric,
  carbs_100g numeric,
  fat_100g numeric,
  updated_at timestamptz default now()
);

-- Row Level Security (mínimo seguro)
alter table public.perfiles enable row level security;
alter table public.registros_diarios enable row level security;
alter table public.checkins enable row level security;
alter table public.alimentos enable row level security;

-- El usuario solo ve/edita sus propios datos
create policy "perfiles_propios" on public.perfiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

create policy "registros_propios" on public.registros_diarios
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "checkins_propios" on public.checkins
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Los alimentos son de lectura pública (caché compartida)
create policy "alimentos_lectura" on public.alimentos
  for select using (true);
